package views;

import models.UserDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SpringLayout;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

public class homePage extends JPanel {
	private JLabel txtTongSoSinhVien;
	private JLabel txtSinhVienTrungBInh;
	private JLabel txtSinhVienXuatSac;
	private JLabel txtSinhVienKha;
	private JLabel txtThongKe;

	public void tongSoSinhVien() throws SQLException, ClassNotFoundException {
		UserDao userDao = new UserDao();
		int[] mangLoai = userDao.tinhSoLuongHocSinh();
		this.txtTongSoSinhVien.setText(Integer.toString(mangLoai[0]));
		this.txtSinhVienXuatSac.setText(Integer.toString(mangLoai[1]));
		this.txtSinhVienKha.setText(Integer.toString(mangLoai[2]));
		this.txtSinhVienTrungBInh.setText(Integer.toString(mangLoai[3]));
		this.txtThongKe.setText("Thống Kê có Khoảng " + Integer.toString(mangLoai[4]) + " / "
				+ Integer.toString(mangLoai[0]) + " sinh viên Chưa có điểm môn nào ");
	}

	public homePage() {
		this.setLayout(new BorderLayout(0, 0));
		JPanel panel = new JPanel();
		panel.setBackground(new Color(255, 255, 255));
		panel.setBorder((Border) null);
		this.add(panel);
		SpringLayout sl_panel = new SpringLayout();
		panel.setLayout(sl_panel);
		JPanel panel_1 = new JPanel();
		sl_panel.putConstraint("South", panel_1, 216, "North", panel);
		panel_1.setBackground(new Color(255, 255, 255));
		sl_panel.putConstraint("North", panel_1, 56, "North", panel);
		sl_panel.putConstraint("West", panel_1, 10, "West", panel);
		panel.add(panel_1);
		panel_1.setLayout(new FlowLayout(1, 5, 5));
		JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setBackground(new Color(255, 255, 255));
		panel_1.add(lblNewLabel);
		sl_panel.putConstraint("South", lblNewLabel, -38, "South", panel);
		sl_panel.putConstraint("East", lblNewLabel, 0, "East", panel);
		lblNewLabel.setHorizontalAlignment(0);
		lblNewLabel.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\FPT_Polytechnic.png"));
		JPanel panel_2 = new JPanel();
		sl_panel.putConstraint("East", panel_1, 0, "East", panel_2);
		sl_panel.putConstraint("West", panel_2, 10, "West", panel);
		sl_panel.putConstraint("East", panel_2, -10, "East", panel);
		panel_2.setBackground(new Color(255, 255, 255));
		sl_panel.putConstraint("North", panel_2, 10, "North", panel);
		sl_panel.putConstraint("South", panel_2, 51, "North", panel);
		panel.add(panel_2);
		JLabel lblNewLabel_1 = new JLabel("PHẦN MỀM QUẢN LÍ SINH VIÊN");
		lblNewLabel_1.setForeground(new Color(255, 128, 64));
		lblNewLabel_1.setFont(new Font("Times New Roman", 1, 30));
		panel_2.add(lblNewLabel_1);
		JPanel panel_3 = new JPanel();
		sl_panel.putConstraint("North", panel_3, 69, "South", panel_1);
		sl_panel.putConstraint("West", panel_3, 0, "West", panel_1);
		sl_panel.putConstraint("East", panel_3, -10, "East", panel);
		panel_3.setBorder(new EmptyBorder(15, 40, 15, 40));
		panel_3.setBackground(new Color(255, 255, 255));
		panel.add(panel_3);
		panel_3.setLayout(new GridLayout(2, 2, 20, 20));
		JPanel panel_6_2_1 = new JPanel();
		panel_6_2_1.setLayout((LayoutManager) null);
		panel_6_2_1.setBackground(new Color(245, 246, 250));
		panel_3.add(panel_6_2_1);
		JPanel panel_7_2_1 = new JPanel();
		panel_7_2_1.setBackground(new Color(0, 168, 255));
		panel_7_2_1.setBounds(0, 0, 118, 88);
		panel_6_2_1.add(panel_7_2_1);
		panel_7_2_1.setLayout((LayoutManager) null);
		JLabel lblNewLabel_2 = new JLabel("");
		lblNewLabel_2.setHorizontalAlignment(0);
		lblNewLabel_2.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\letter-a.png"));
		lblNewLabel_2.setBounds(0, 0, 118, 88);
		panel_7_2_1.add(lblNewLabel_2);
		this.txtSinhVienXuatSac = new JLabel("100");
		this.txtSinhVienXuatSac.setForeground(new Color(39, 39, 39));
		this.txtSinhVienXuatSac.setFont(new Font("Trebuchet MS", 1, 35));
		this.txtSinhVienXuatSac.setBounds(128, 10, 187, 36);
		panel_6_2_1.add(this.txtSinhVienXuatSac);
		JLabel lblNewLabel_2_1_2_1 = new JLabel("Sinh viên xuất sắc");
		lblNewLabel_2_1_2_1.setFont(new Font("Tahoma", 0, 15));
		lblNewLabel_2_1_2_1.setBounds(128, 36, 187, 48);
		panel_6_2_1.add(lblNewLabel_2_1_2_1);
		JPanel panel_6_2_2 = new JPanel();
		panel_6_2_2.setLayout((LayoutManager) null);
		panel_6_2_2.setBackground(new Color(245, 246, 250));
		panel_3.add(panel_6_2_2);
		JPanel panel_7_2_2 = new JPanel();
		panel_7_2_2.setBackground(new Color(232, 65, 24));
		panel_7_2_2.setBounds(0, 0, 118, 88);
		panel_6_2_2.add(panel_7_2_2);
		panel_7_2_2.setLayout((LayoutManager) null);
		JLabel lblNewLabel_3 = new JLabel("");
		lblNewLabel_3.setHorizontalAlignment(0);
		lblNewLabel_3.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\letter-b.png"));
		lblNewLabel_3.setBounds(0, 0, 118, 88);
		panel_7_2_2.add(lblNewLabel_3);
		this.txtSinhVienKha = new JLabel("34");
		this.txtSinhVienKha.setForeground(new Color(39, 39, 39));
		this.txtSinhVienKha.setFont(new Font("Trebuchet MS", 1, 35));
		this.txtSinhVienKha.setBounds(126, 10, 189, 36);
		panel_6_2_2.add(this.txtSinhVienKha);
		JLabel lblNewLabel_2_1_2_2 = new JLabel("Sinh Viên Khá ");
		lblNewLabel_2_1_2_2.setFont(new Font("Tahoma", 0, 15));
		lblNewLabel_2_1_2_2.setBounds(126, 36, 189, 48);
		panel_6_2_2.add(lblNewLabel_2_1_2_2);
		JPanel panel_6_2 = new JPanel();
		panel_6_2.setLayout((LayoutManager) null);
		panel_6_2.setBackground(new Color(245, 246, 250));
		panel_3.add(panel_6_2);
		JPanel panel_7_2 = new JPanel();
		panel_7_2.setBackground(new Color(16, 172, 132));
		panel_7_2.setBounds(0, 0, 118, 88);
		panel_6_2.add(panel_7_2);
		panel_7_2.setLayout((LayoutManager) null);
		JLabel lblNewLabel_4 = new JLabel("");
		lblNewLabel_4.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\letter-c.png"));
		lblNewLabel_4.setHorizontalAlignment(0);
		lblNewLabel_4.setBounds(0, 0, 118, 88);
		panel_7_2.add(lblNewLabel_4);
		this.txtSinhVienTrungBInh = new JLabel("48");
		this.txtSinhVienTrungBInh.setForeground(new Color(39, 39, 39));
		this.txtSinhVienTrungBInh.setFont(new Font("Trebuchet MS", 1, 35));
		this.txtSinhVienTrungBInh.setBounds(128, 10, 187, 36);
		panel_6_2.add(this.txtSinhVienTrungBInh);
		JLabel lblNewLabel_2_1_2 = new JLabel("Sinh viên trung bình");
		lblNewLabel_2_1_2.setFont(new Font("Tahoma", 0, 15));
		lblNewLabel_2_1_2.setBounds(128, 38, 187, 46);
		panel_6_2.add(lblNewLabel_2_1_2);
		JPanel panel_6_2_3 = new JPanel();
		panel_6_2_3.setLayout((LayoutManager) null);
		panel_6_2_3.setBackground(new Color(245, 246, 250));
		panel_3.add(panel_6_2_3);
		JPanel panel_7_2_3 = new JPanel();
		panel_7_2_3.setBackground(new Color(254, 202, 87));
		panel_7_2_3.setBounds(0, 0, 118, 88);
		panel_6_2_3.add(panel_7_2_3);
		panel_7_2_3.setLayout((LayoutManager) null);
		JLabel lblNewLabel_5 = new JLabel("");
		lblNewLabel_5.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\students.png"));
		lblNewLabel_5.setHorizontalAlignment(0);
		lblNewLabel_5.setBounds(10, 10, 98, 68);
		panel_7_2_3.add(lblNewLabel_5);
		this.txtTongSoSinhVien = new JLabel("194");
		this.txtTongSoSinhVien.setForeground(new Color(39, 39, 39));
		this.txtTongSoSinhVien.setFont(new Font("Trebuchet MS", 1, 35));
		this.txtTongSoSinhVien.setBounds(126, 10, 189, 36);
		panel_6_2_3.add(this.txtTongSoSinhVien);
		JLabel lblNewLabel_2_1_2_3 = new JLabel("Tổng số sinh viên");
		lblNewLabel_2_1_2_3.setFont(new Font("Tahoma", 0, 15));
		lblNewLabel_2_1_2_3.setBounds(126, 36, 189, 48);
		panel_6_2_3.add(lblNewLabel_2_1_2_3);
		JPanel panel_4 = new JPanel();
		sl_panel.putConstraint("North", panel_4, 6, "South", panel_1);
		sl_panel.putConstraint("South", panel_4, -353, "South", panel);
		panel_4.setBackground(new Color(255, 255, 255));
		sl_panel.putConstraint("West", panel_4, 0, "West", panel_1);
		sl_panel.putConstraint("East", panel_4, 0, "East", panel_1);
		panel.add(panel_4);
		panel_4.setLayout(new FlowLayout(1, 5, 5));
		JPanel panel_5 = new JPanel();
		sl_panel.putConstraint("North", panel_5, 517, "North", panel);
		sl_panel.putConstraint("South", panel_3, -6, "North", panel_5);
		sl_panel.putConstraint("West", panel_5, 10, "West", panel);
		sl_panel.putConstraint("South", panel_5, -10, "South", panel);
		sl_panel.putConstraint("East", panel_5, 0, "East", panel_1);
		panel_5.setBackground(new Color(255, 255, 255));
		panel_5.setBorder(new EmptyBorder(0, 30, 0, 30));
		panel.add(panel_5);
		panel_5.setLayout(new MigLayout("", "[grow]", "[grow]"));
		JPanel panel_6 = new JPanel();
		panel_6.setBackground(new Color(245, 246, 250));
		panel_5.add(panel_6, "cell 0 0,grow");
		panel_6.setLayout((LayoutManager) null);
		JPanel panel_7 = new JPanel();
		panel_7.setBackground(new Color(255, 255, 255));
		panel_7.setBounds(0, 0, 139, 91);
		panel_6.add(panel_7);
		panel_7.setLayout((LayoutManager) null);
		JLabel lblNewLabel_6 = new JLabel("");
		lblNewLabel_6.setHorizontalAlignment(0);
		lblNewLabel_6.setIcon(new ImageIcon("D:\\JAVA\\BAITHII_PD07906\\sourceCode\\imgs\\statistics-svgrepo-com.png"));
		lblNewLabel_6.setBounds(0, 0, 139, 113);
		panel_7.add(lblNewLabel_6);
		this.txtThongKe = new JLabel("Thống kê có khoảng 100/200 sinh viên chưa có điểm môn nào ");
		this.txtThongKe.setFont(new Font("Tahoma", 0, 15));
		this.txtThongKe.setBounds(149, 0, 497, 67);
		panel_6.add(this.txtThongKe);

		try {
			this.tongSoSinhVien();
		} catch (SQLException var30) {
			System.out.println(var30.getMessage() + "dòng 32-40 class: homePage");
		} catch (ClassNotFoundException var31) {
			System.out.println(var31.getMessage() + "dòng 32-40 class: homePage");
		}

	}
}